<#
.SYNOPSIS
  Local release helper for DeskRealm.

.DESCRIPTION
  Publishes a DeskRealm update to GitHub using the repository workflow:
    1. Ensure GitHub CLI authentication is configured.
    2. Generate GitHub release notes from CHANGELOG.md.
    3. Stage, commit and push repository changes.
    4. Create/push an annotated release tag.
    5. Wait for the GitHub Release generated by Actions and update its notes.

  This tracked, secret-free script intentionally lives in .local-tools/.
  It is a maintainer convenience script, not part of the public runtime package.
#>

[CmdletBinding()]
param(
  [Parameter(Mandatory = $true)]
  [ValidatePattern('^v?\d+\.\d+\.\d+([-.][A-Za-z0-9.]+)?$')]
  [string]$Version,

  [string]$Repository = 'ekimaku/DeskRealm',
  [string]$Remote = 'origin',
  [string]$Branch = 'main',
  [string]$CommitMessage = '',

  [switch]$DryRun,
  [switch]$SkipAuth,
  [switch]$ForceWithLease,
  [switch]$NoTag,
  [switch]$MoveExistingTag,
  [switch]$SkipLocalBuild,
  [bool]$UpdateGitHubReleaseFromChangelog = $true,
  [bool]$OpenReleasePage = $true,

  [int]$ReleasePollAttempts = 36,
  [int]$ReleasePollDelaySeconds = 10
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Write-Step {
  param([Parameter(Mandatory = $true)][string]$Message)
  Write-Host ''
  Write-Host ('==> ' + $Message) -ForegroundColor Cyan
}

function Write-Ok {
  param([Parameter(Mandatory = $true)][string]$Message)
  Write-Host ('OK  ' + $Message) -ForegroundColor Green
}

function Write-LocalWarn {
  param([Parameter(Mandatory = $true)][string]$Message)
  Write-Host ('WARN ' + $Message) -ForegroundColor Yellow
}

function Invoke-Checked {
  param(
    [Parameter(Mandatory = $true)][string]$File,
    [Parameter(ValueFromRemainingArguments = $true)][string[]]$CommandArgs = @()
  )

  $cmd = ($File + ' ' + ($CommandArgs -join ' ')).Trim()
  if ($DryRun) {
    Write-Host ('DRY ' + $cmd) -ForegroundColor DarkGray
    return @()
  }

  Write-Host ('> ' + $cmd) -ForegroundColor DarkGray
  & $File @CommandArgs
  if ($LASTEXITCODE -ne 0) {
    throw ('Command failed with exit code {0}: {1}' -f $LASTEXITCODE, $cmd)
  }
}

function Invoke-Capture {
  param(
    [Parameter(Mandatory = $true)][string]$File,
    [Parameter(ValueFromRemainingArguments = $true)][string[]]$CommandArgs = @()
  )

  $cmd = ($File + ' ' + ($CommandArgs -join ' ')).Trim()
  Write-Host ('> ' + $cmd) -ForegroundColor DarkGray
  $output = & $File @CommandArgs 2>&1
  $exit = $LASTEXITCODE
  if ($exit -ne 0) {
    throw ('Command failed with exit code {0}: {1}`n{2}' -f $exit, $cmd, ($output -join [Environment]::NewLine))
  }
  return $output
}

function Test-CommandExists {
  param([Parameter(Mandatory = $true)][string]$Command)
  return $null -ne (Get-Command $Command -ErrorAction SilentlyContinue)
}

function Get-GitRoot {
  $root = (Invoke-Capture git rev-parse --show-toplevel | Select-Object -First 1).Trim()
  if (-not $root) { throw 'Not inside a Git repository.' }
  return $root
}

function Normalize-VersionTag {
  param([Parameter(Mandatory = $true)][string]$InputVersion)
  if ($InputVersion.StartsWith('v')) { return $InputVersion }
  return ('v' + $InputVersion)
}

function Get-VersionNumber {
  param([Parameter(Mandatory = $true)][string]$InputVersion)
  if ($InputVersion.StartsWith('v')) { return $InputVersion.Substring(1) }
  return $InputVersion
}

function Get-ChangelogSection {
  param(
    [Parameter(Mandatory = $true)][string]$ChangelogPath,
    [Parameter(Mandatory = $true)][string]$Tag,
    [Parameter(Mandatory = $true)][string]$VersionNumber
  )

  if (-not (Test-Path $ChangelogPath)) {
    throw ('CHANGELOG file not found: {0}' -f $ChangelogPath)
  }

  $lines = Get-Content -Path $ChangelogPath -Encoding UTF8
  $pattern = '^##\s+' + [regex]::Escape($Tag) + '(\s|$)|^##\s+v?' + [regex]::Escape($VersionNumber) + '(\s|$)'

  $start = -1
  for ($i = 0; $i -lt $lines.Count; $i++) {
    if ($lines[$i] -match $pattern) {
      $start = $i
      break
    }
  }

  if ($start -lt 0) {
    throw ('No CHANGELOG section found for {0}. Add one before releasing.' -f $Tag)
  }

  $end = $lines.Count
  for ($i = $start + 1; $i -lt $lines.Count; $i++) {
    if ($lines[$i] -match '^##\s+') {
      $end = $i
      break
    }
  }

  $section = $lines[$start..($end - 1)]
  return ($section -join [Environment]::NewLine).Trim()
}

function New-ReleaseNotesFromChangelog {
  param(
    [Parameter(Mandatory = $true)][string]$Root,
    [Parameter(Mandatory = $true)][string]$Tag,
    [Parameter(Mandatory = $true)][string]$VersionNumber
  )

  $changelogPath = Join-Path $Root 'CHANGELOG.md'
  $section = Get-ChangelogSection -ChangelogPath $changelogPath -Tag $Tag -VersionNumber $VersionNumber

  $sectionLines = $section -split '\r?\n'
  if ($sectionLines.Count -gt 1) {
    $bodyLines = $sectionLines[1..($sectionLines.Count - 1)]
  } else {
    $bodyLines = @()
  }

  $body = ($bodyLines -join [Environment]::NewLine).Trim()
  if (-not $body) { $body = '- Maintenance release.' }

  $workDir = Join-Path $Root '.release-work'
  if (-not (Test-Path $workDir)) {
    New-Item -ItemType Directory -Path $workDir | Out-Null
  }

  $notesPath = Join-Path $workDir ('release-notes-{0}-from-changelog.md' -f $Tag)
  $notesLines = @(
    ('# DeskRealm {0}' -f $Tag),
    '',
    $body,
    '',
    '---',
    '',
    'Generated from CHANGELOG.md by .local-tools/Publish-DeskRealmRelease.ps1.'
  )

  Set-Content -Path $notesPath -Value ($notesLines -join [Environment]::NewLine) -Encoding UTF8
  return $notesPath
}

function Ensure-GhAuth {
  if ($SkipAuth) {
    Write-LocalWarn 'Skipping GitHub CLI auth checks because -SkipAuth was passed.'
    return
  }

  if (-not (Test-CommandExists 'gh')) {
    throw 'GitHub CLI (gh) is not installed. Install it with: winget install GitHub.cli'
  }

  Write-Step 'Checking GitHub CLI authentication'
  & gh auth status --hostname github.com *> $null
  if ($LASTEXITCODE -ne 0) {
    Write-LocalWarn 'GitHub CLI is not authenticated. Opening browser login.'
    Invoke-Checked gh auth login --hostname github.com --git-protocol https --web
  } else {
    Write-Ok 'GitHub CLI authentication found.'
  }

  Write-Step 'Configuring Git to use GitHub CLI credentials'
  Invoke-Checked gh auth setup-git --hostname github.com
}

function Ensure-Remote {
  param(
    [Parameter(Mandatory = $true)][string]$Repo,
    [Parameter(Mandatory = $true)][string]$RemoteName
  )

  $expectedHttps = ('https://github.com/{0}.git' -f $Repo)
  & git remote get-url $RemoteName *> $null
  if ($LASTEXITCODE -ne 0) {
    Write-LocalWarn ('Remote {0} not found. Adding {1}.' -f $RemoteName, $expectedHttps)
    Invoke-Checked git remote add $RemoteName $expectedHttps
    return
  }

  $current = (Invoke-Capture git remote get-url $RemoteName | Select-Object -First 1).Trim()
  Write-Ok ('Remote {0}: {1}' -f $RemoteName, $current)
}

function Ensure-Branch {
  param([Parameter(Mandatory = $true)][string]$BranchName)
  $currentBranch = (Invoke-Capture git branch --show-current | Select-Object -First 1).Trim()
  if ($currentBranch -ne $BranchName) {
    Write-LocalWarn ('Current branch is {0}. Switching/renaming to {1}.' -f $currentBranch, $BranchName)
    Invoke-Checked git branch -M $BranchName
  }
}

function Commit-Changes {
  param([Parameter(Mandatory = $true)][string]$Message)

  Write-Step 'Staging repository changes'
  Invoke-Checked git add -A

  $status = Invoke-Capture git status --porcelain
  if (-not $status -or $status.Count -eq 0) {
    Write-LocalWarn 'No repository changes to commit.'
    return $false
  }

  Write-Step 'Committing changes'
  Invoke-Checked git commit -m $Message
  return $true
}

function Push-Main {
  param(
    [Parameter(Mandatory = $true)][string]$RemoteName,
    [Parameter(Mandatory = $true)][string]$BranchName,
    [switch]$UseForceWithLease
  )

  Write-Step ('Pushing {0}' -f $BranchName)
  if ($UseForceWithLease) {
    Invoke-Checked git push --force-with-lease $RemoteName $BranchName
  } else {
    Invoke-Checked git push $RemoteName $BranchName
  }
}

function Ensure-Tag {
  param(
    [Parameter(Mandatory = $true)][string]$Tag,
    [Parameter(Mandatory = $true)][string]$RemoteName,
    [switch]$MoveTag
  )

  if ($NoTag) {
    Write-LocalWarn 'Skipping tag creation because -NoTag was passed.'
    return
  }

  Write-Step ('Preparing tag {0}' -f $Tag)

  # Avoid git rev-parse for missing tags. On PowerShell, native stderr from a
  # missing revision can surface as a NativeCommandError before we can inspect
  # LASTEXITCODE. `git tag --list <pattern>` exits cleanly when there is no match.
  $localTagMatches = Invoke-Capture git tag --list $Tag
  $localTagExists = $false
  foreach ($tagMatch in $localTagMatches) {
    if ($tagMatch.Trim() -eq $Tag) {
      $localTagExists = $true
      break
    }
  }

  # Do not use --exit-code here: an absent remote tag is a normal release path.
  $remoteTagMatches = Invoke-Capture git ls-remote --tags $RemoteName ('refs/tags/{0}' -f $Tag)
  $remoteTagExists = $false
  foreach ($remoteTagMatch in $remoteTagMatches) {
    if ($remoteTagMatch -match ('refs/tags/' + [regex]::Escape($Tag) + '$')) {
      $remoteTagExists = $true
      break
    }
  }

  if (($localTagExists -or $remoteTagExists) -and -not $MoveTag) {
    throw ('Tag {0} already exists. Use -MoveExistingTag only if you intentionally want to replace it.' -f $Tag)
  }

  if ($MoveTag) {
    if ($localTagExists) { Invoke-Checked git tag -d $Tag }
    if ($remoteTagExists) { Invoke-Checked git push $RemoteName (':refs/tags/{0}' -f $Tag) }
  }

  if (-not $localTagExists -or $MoveTag) {
    Invoke-Checked git tag -a $Tag -m ('DeskRealm {0}' -f $Tag)
  }

  Write-Step ('Pushing tag {0}' -f $Tag)
  Invoke-Checked git push $RemoteName $Tag
}

function Wait-And-UpdateReleaseNotes {
  param(
    [Parameter(Mandatory = $true)][string]$Repo,
    [Parameter(Mandatory = $true)][string]$Tag,
    [Parameter(Mandatory = $true)][string]$NotesPath,
    [Parameter(Mandatory = $true)][int]$Attempts,
    [Parameter(Mandatory = $true)][int]$DelaySeconds
  )

  if (-not $UpdateGitHubReleaseFromChangelog) {
    Write-LocalWarn 'Skipping GitHub Release body update because release-note update is disabled.'
    return
  }

  if ($DryRun) {
    Write-LocalWarn ('Dry-run: would wait for GitHub Release {0} and update notes from {1}.' -f $Tag, $NotesPath)
    return
  }

  if ($NoTag) {
    Write-LocalWarn 'Skipping GitHub Release body update because -NoTag was passed.'
    return
  }

  Write-Step ('Waiting for GitHub Release {0}' -f $Tag)
  for ($i = 1; $i -le $Attempts; $i++) {
    # Keep this compatible with Windows PowerShell 5.1 and PowerShell 7+.
    # Do not use System.Diagnostics.ProcessStartInfo.ArgumentList: it is not
    # available in older Windows PowerShell/.NET Framework hosts.
    # Also suppress native stderr because "release not found" is a normal
    # polling state while GitHub Actions is still creating the release.
    $previousErrorActionPreference = $ErrorActionPreference
    $ErrorActionPreference = 'SilentlyContinue'
    try {
      & gh release view $Tag --repo $Repo *> $null
      $releaseViewExitCode = $LASTEXITCODE
    }
    finally {
      $ErrorActionPreference = $previousErrorActionPreference
    }

    if ($releaseViewExitCode -eq 0) {
      Write-Ok ('Release {0} found. Updating notes from CHANGELOG-generated file.' -f $Tag)
      Invoke-Checked gh release edit $Tag --repo $Repo --title ('DeskRealm {0}' -f $Tag) --notes-file $NotesPath
      return
    }

    Write-Host ('Release not available yet ({0}/{1}). Waiting {2} sec...' -f $i, $Attempts, $DelaySeconds) -ForegroundColor DarkGray
    Start-Sleep -Seconds $DelaySeconds
  }

  Write-LocalWarn ('Release {0} was not found after waiting. The GitHub Actions workflow may still be running.' -f $Tag)
  Write-LocalWarn ('You can update notes later with gh release edit {0} --repo {1} --notes-file <notes-file>' -f $Tag, $Repo)
}

function Invoke-LocalReleasePreparation {
  param(
    [Parameter(Mandatory = $true)][string]$Root,
    [Parameter(Mandatory = $true)][string]$VersionNumber
  )

  $prepareScript = Join-Path $Root 'scripts\Prepare-GitHubRelease.ps1'
  if (-not (Test-Path -LiteralPath $prepareScript)) {
    throw ('Tracked release preparation script is missing: {0}' -f $prepareScript)
  }

  if ($DryRun) {
    Write-LocalWarn ('Dry-run: would execute {0} -Version {1} before staging.' -f $prepareScript, $VersionNumber)
    return
  }

  Write-Step 'Running tracked local release preparation'
  $arguments = @('-Version', $VersionNumber)
  if ($SkipLocalBuild) { $arguments += '-SkipBuild' }
  & $prepareScript @arguments
}

# Main
$tag = Normalize-VersionTag $Version
$versionNumber = Get-VersionNumber $Version

Write-Step ('DeskRealm release helper - {0}' -f $tag)
if (-not (Test-CommandExists 'git')) { throw 'Git is not installed or not in PATH.' }

Ensure-GhAuth

$root = Get-GitRoot
Set-Location $root
Write-Ok ('Repository root: {0}' -f $root)

Ensure-Remote -Repo $Repository -RemoteName $Remote
Ensure-Branch -BranchName $Branch

Invoke-LocalReleasePreparation -Root $root -VersionNumber $versionNumber

Write-Step 'Fetching remote state'
Invoke-Checked git fetch $Remote --tags

$notesPath = New-ReleaseNotesFromChangelog -Root $root -Tag $tag -VersionNumber $versionNumber
Write-Ok ('CHANGELOG release notes generated: {0}' -f $notesPath)

if (-not $CommitMessage) {
  $CommitMessage = ('Release DeskRealm {0}' -f $tag)
}

Commit-Changes -Message $CommitMessage | Out-Null
Push-Main -RemoteName $Remote -BranchName $Branch -UseForceWithLease:$ForceWithLease
Ensure-Tag -Tag $tag -RemoteName $Remote -MoveTag:$MoveExistingTag
Wait-And-UpdateReleaseNotes -Repo $Repository -Tag $tag -NotesPath $notesPath -Attempts $ReleasePollAttempts -DelaySeconds $ReleasePollDelaySeconds

if ($OpenReleasePage) {
  Write-Step 'Opening GitHub release page'
  if (-not $DryRun) { gh release view $tag --repo $Repository --web }
}

Write-Host ''
Write-Host ('DeskRealm {0} publication flow completed.' -f $tag) -ForegroundColor Green
